export type LibraryPresenter = {
  name: string;
  slug: string;
  gender: "female" | "male";
  ageRange: string;
  region: string;
  skinTone: string;
  hair: string;
  bodyType: string;
  clothingStyle: string;
  professionalStyle: string;
  personality: string;
  voiceId: string;
  accent: string;
  languages: string[];
  speakingTone: string;
  categories: string[];
  studioStyle: string;
  bio: string;
  portraitUrl?: string;
};

export const LIBRARY_PRESENTERS: LibraryPresenter[] = [
  {
    name: "Amara Okonkwo",
    slug: "amara-okonkwo",
    gender: "female",
    ageRange: "28-34",
    region: "Nigeria / West Africa",
    skinTone: "Deep mahogany",
    hair: "Sculpted braided crown",
    bodyType: "Athletic",
    clothingStyle: "Tailored gold-trim blouse",
    professionalStyle: "Editorial beauty director",
    personality: "Warm, precise, quietly magnetic",
    voiceId: "amara-warm",
    accent: "Nigerian",
    languages: ["en", "yo", "ig"],
    speakingTone: "Luxury",
    categories: ["Fashion & Beauty", "Luxury", "Ecommerce"],
    studioStyle: "Editorial fashion set",
    bio: "A Lagos-born studio presenter with couture posture and a calm luxury cadence. Built for beauty, fashion and premium retail films.",
    portraitUrl: "/presenters/amara-okonkwo.png",
  },
  {
    name: "Chinedu Adebayo",
    slug: "chinedu-adebayo",
    gender: "male",
    ageRange: "36-44",
    region: "Nigeria / West Africa",
    skinTone: "Rich espresso",
    hair: "Close cropped with a sharp line",
    bodyType: "Broad professional",
    clothingStyle: "Navy suit, open collar",
    professionalStyle: "Boardroom host",
    personality: "Grounded, articulate, trusted",
    voiceId: "chinedu-confident",
    accent: "Nigerian",
    languages: ["en", "yo", "ha"],
    speakingTone: "Professional",
    categories: ["Business & Corporate", "General Marketing", "Real Estate"],
    studioStyle: "Modern glass office",
    bio: "A senior corporate presenter who makes complex offers feel clear. Ideal for finance, consulting and institutional brand films.",
  },
  {
    name: "Layla Al-Hassan",
    slug: "layla-al-hassan",
    gender: "female",
    ageRange: "30-38",
    region: "Arab / Middle Eastern",
    skinTone: "Warm olive",
    hair: "Long dark waves, half-up silk",
    bodyType: "Elegant slim",
    clothingStyle: "Ivory silk abaya-inspired tailoring",
    professionalStyle: "Quiet luxury host",
    personality: "Poised, gracious, exacting",
    voiceId: "layla-luxe",
    accent: "Arabic",
    languages: ["ar", "en", "fr"],
    speakingTone: "Luxury",
    categories: ["Luxury", "Fashion & Beauty", "Real Estate"],
    studioStyle: "Luxury marble lounge",
    bio: "A Gulf-inspired luxury ambassador for jewelry, hospitality and high-end property. Never flashy — always composed.",
  },
  {
    name: "Omar Farid",
    slug: "omar-farid",
    gender: "male",
    ageRange: "38-46",
    region: "Arab / Middle Eastern",
    skinTone: "Medium bronze",
    hair: "Textured crop, groomed beard",
    bodyType: "Tall refined",
    clothingStyle: "Charcoal thobe-inspired studio coat",
    professionalStyle: "Property and hospitality guide",
    personality: "Assured, courteous, cinematic",
    voiceId: "omar-deep",
    accent: "Arabic",
    languages: ["ar", "en"],
    speakingTone: "Confident",
    categories: ["Real Estate", "Luxury", "Restaurants & Hospitality"],
    studioStyle: "Evening city terrace",
    bio: "A cinematic male host for destination real estate, hotels and premium services across Arabic and English campaigns.",
  },
  {
    name: "Maya Chen",
    slug: "maya-chen",
    gender: "female",
    ageRange: "26-32",
    region: "United States",
    skinTone: "Light gold",
    hair: "Straight shoulder-length, side part",
    bodyType: "Petite athletic",
    clothingStyle: "Soft tech blazer over knit",
    professionalStyle: "Product storyteller",
    personality: "Clear, curious, optimistic",
    voiceId: "maya-bright",
    accent: "American",
    languages: ["en", "es"],
    speakingTone: "Friendly",
    categories: ["Technology", "Apps & Software", "Ecommerce"],
    studioStyle: "Clean product cyclorama",
    bio: "A San Francisco product presenter who can walk through an interface without sounding like a tutorial.",
  },
  {
    name: "Jordan Hale",
    slug: "jordan-hale",
    gender: "male",
    ageRange: "32-40",
    region: "United States",
    skinTone: "Fair warm",
    hair: "Tousled brown, short sides",
    bodyType: "Average athletic",
    clothingStyle: "Denim shirt, studio jacket",
    professionalStyle: "Direct-to-camera retail host",
    personality: "Energetic, honest, commercial",
    voiceId: "jordan-sales",
    accent: "American",
    languages: ["en"],
    speakingTone: "Sales-focused",
    categories: ["Ecommerce", "General Marketing", "Lifestyle"],
    studioStyle: "Soft daylight loft",
    bio: "A conversion-minded presenter for product drops, offers and social ads that still feel human.",
  },
  {
    name: "Seo-yeon Park",
    slug: "seo-yeon-park",
    gender: "female",
    ageRange: "24-30",
    region: "South Korea",
    skinTone: "Porcelain peach",
    hair: "Glossy long layers, center part",
    bodyType: "Slim editorial",
    clothingStyle: "Minimal cream knit set",
    professionalStyle: "K-beauty campaign lead",
    personality: "Soft, polished, precise",
    voiceId: "seoyeon-soft",
    accent: "Korean",
    languages: ["ko", "en"],
    speakingTone: "Warm",
    categories: ["Fashion & Beauty", "Lifestyle", "Ecommerce"],
    studioStyle: "Wellness spa light",
    bio: "A Seoul beauty presenter with restrained gesture and luminous stillness. Built for skincare, fashion and lifestyle films.",
  },
  {
    name: "Yuna Han",
    slug: "yuna-han",
    gender: "female",
    ageRange: "26-32",
    region: "South Korea",
    skinTone: "Porcelain peach",
    hair: "Long dark layers, soft center part",
    bodyType: "Slim editorial",
    clothingStyle: "Cream ribbed knit and tailored trousers",
    professionalStyle: "Standing fashion presenter",
    personality: "Warm, expressive, camera-native",
    voiceId: "yuna-warm",
    accent: "Korean",
    languages: ["ko", "en"],
    speakingTone: "Warm",
    categories: ["Fashion & Beauty", "Lifestyle", "Luxury"],
    studioStyle: "Editorial fashion set",
    bio: "A Seoul fashion presenter who talks with her whole body — walking, turning, pointing, and smiling while she speaks. Built for apparel, lookbooks and lifestyle films.",
    portraitUrl: "/presenters/yuna-han.png",
  },
  {
    name: "Min-jun Kim",
    slug: "min-jun-kim",
    gender: "male",
    ageRange: "27-33",
    region: "South Korea",
    skinTone: "Light neutral",
    hair: "Modern two-block, dark",
    bodyType: "Lean",
    clothingStyle: "Black technical overshirt",
    professionalStyle: "App and gadget demonstrator",
    personality: "Crisp, modern, understated",
    voiceId: "minjun-tech",
    accent: "Korean",
    languages: ["ko", "en", "ja"],
    speakingTone: "Professional",
    categories: ["Apps & Software", "Technology", "Lifestyle"],
    studioStyle: "Premium dark studio",
    bio: "A precise mobile-product presenter who treats UI like cinema. Strong for fintech, camera apps and consumer electronics.",
  },
  {
    name: "Hana Sato",
    slug: "hana-sato",
    gender: "female",
    ageRange: "29-36",
    region: "Japan",
    skinTone: "Ivory rose",
    hair: "Sleek bob with a soft fringe",
    bodyType: "Petite",
    clothingStyle: "Stone linen shirt dress",
    professionalStyle: "Lifestyle editor",
    personality: "Gentle, intelligent, unhurried",
    voiceId: "hana-calm",
    accent: "Japanese",
    languages: ["ja", "en"],
    speakingTone: "Calm",
    categories: ["Lifestyle", "Healthcare & Wellness", "Restaurants & Hospitality"],
    studioStyle: "Warm lifestyle kitchen",
    bio: "A Tokyo lifestyle presenter for hospitality, wellness and considered everyday products.",
  },
  {
    name: "Kenji Watanabe",
    slug: "kenji-watanabe",
    gender: "male",
    ageRange: "40-48",
    region: "Japan",
    skinTone: "Light olive",
    hair: "Silver-touched crop",
    bodyType: "Slim professional",
    clothingStyle: "Charcoal kimono-collar jacket",
    professionalStyle: "Craft and technology narrator",
    personality: "Measured, thoughtful, authoritative",
    voiceId: "kenji-low",
    accent: "Japanese",
    languages: ["ja", "en"],
    speakingTone: "Professional",
    categories: ["Technology", "Business & Corporate", "Luxury"],
    studioStyle: "Premium dark studio",
    bio: "A senior Japanese presenter for precision products, enterprise tools and heritage-meets-tech stories.",
  },
  {
    name: "Anja Vogel",
    slug: "anja-vogel",
    gender: "female",
    ageRange: "34-42",
    region: "Germany / Europe",
    skinTone: "Fair cool",
    hair: "Ash blonde chignon",
    bodyType: "Tall slim",
    clothingStyle: "Bone tailoring, architectural jewelry",
    professionalStyle: "Corporate keynote presenter",
    personality: "Direct, elegant, unsentimental",
    voiceId: "anja-clear",
    accent: "German",
    languages: ["de", "en", "fr"],
    speakingTone: "Professional",
    categories: ["Business & Corporate", "Technology", "General Marketing"],
    studioStyle: "Modern glass office",
    bio: "A Berlin-based corporate presenter for B2B, industrial design and European brand introductions.",
  },
  {
    name: "Lukas Weber",
    slug: "lukas-weber",
    gender: "male",
    ageRange: "33-41",
    region: "Germany / Europe",
    skinTone: "Fair warm",
    hair: "Wavy chestnut, neatly parted",
    bodyType: "Average fit",
    clothingStyle: "Soft sage overshirt, open collar",
    professionalStyle: "Healthcare explainer",
    personality: "Calm, trustworthy, human",
    voiceId: "lukas-warm",
    accent: "German",
    languages: ["de", "en"],
    speakingTone: "Calm",
    categories: ["Healthcare & Wellness", "Apps & Software", "General Marketing"],
    studioStyle: "Wellness spa light",
    bio: "A clinician-toned presenter for health, wellness and serious consumer services — never clinical to the point of cold.",
  },
  {
    name: "Isabella Rossi",
    slug: "isabella-rossi",
    gender: "female",
    ageRange: "31-39",
    region: "Europe / Italy",
    skinTone: "Sun-warmed olive",
    hair: "Auburn waves, loose",
    bodyType: "Curvy elegant",
    clothingStyle: "Terracotta silk blouse",
    professionalStyle: "Hospitality storyteller",
    personality: "Generous, vivid, inviting",
    voiceId: "isabella-rich",
    accent: "Neutral",
    languages: ["en", "es", "fr"],
    speakingTone: "Warm",
    categories: ["Restaurants & Hospitality", "Lifestyle", "Luxury"],
    studioStyle: "Warm lifestyle kitchen",
    bio: "A Mediterranean hospitality presenter for restaurants, travel and food brands that want appetite and atmosphere.",
  },
  {
    name: "Priya Raman",
    slug: "priya-raman",
    gender: "female",
    ageRange: "27-34",
    region: "South Asia / Global",
    skinTone: "Warm tan",
    hair: "Long dark curls, half tied",
    bodyType: "Average",
    clothingStyle: "Saffron-trim modern kurta jacket",
    professionalStyle: "Software and education guide",
    personality: "Bright, lucid, encouraging",
    voiceId: "priya-bright",
    accent: "Neutral",
    languages: ["en", "hi"],
    speakingTone: "Conversational",
    categories: ["Apps & Software", "Technology", "General Marketing"],
    studioStyle: "Clean product cyclorama",
    bio: "A global software presenter who can make a dense product feel like an invitation.",
  },
  {
    name: "Kwame Mensah",
    slug: "kwame-mensah",
    gender: "male",
    ageRange: "29-36",
    region: "Ghana / West Africa",
    skinTone: "Deep bronze",
    hair: "Short twists",
    bodyType: "Athletic",
    clothingStyle: "Kente-accent studio polo",
    professionalStyle: "Lifestyle and culture host",
    personality: "Charismatic, easy, magnetic",
    voiceId: "kwame-energy",
    accent: "Ghanaian",
    languages: ["en", "ha"],
    speakingTone: "Energetic",
    categories: ["Lifestyle", "Ecommerce", "General Marketing"],
    studioStyle: "Soft daylight loft",
    bio: "An Accra lifestyle host for culture-forward consumer brands, apps and social campaigns.",
  },
  {
    name: "Sofia Alvarez",
    slug: "sofia-alvarez",
    gender: "female",
    ageRange: "25-32",
    region: "Latin America / Global",
    skinTone: "Golden caramel",
    hair: "Voluminous dark curls",
    bodyType: "Hourglass",
    clothingStyle: "Rose satin slip blazer",
    professionalStyle: "Fashion campaign lead",
    personality: "Playful, bold, camera-native",
    voiceId: "sofia-glow",
    accent: "Spanish",
    languages: ["es", "en", "pt"],
    speakingTone: "Energetic",
    categories: ["Fashion & Beauty", "Ecommerce", "Lifestyle"],
    studioStyle: "Editorial fashion set",
    bio: "A bilingual fashion presenter for beauty drops, apparel and social-first brand films.",
  },
  {
    name: "Elias Nordström",
    slug: "elias-nordstrom",
    gender: "male",
    ageRange: "37-45",
    region: "Nordic / Europe",
    skinTone: "Fair cool",
    hair: "Ash brown, swept back",
    bodyType: "Tall lean",
    clothingStyle: "Wool taupe overcoat look",
    professionalStyle: "Architecture and property narrator",
    personality: "Quiet, design-led, sincere",
    voiceId: "elias-low",
    accent: "Neutral",
    languages: ["en", "de"],
    speakingTone: "Calm",
    categories: ["Real Estate", "Luxury", "Lifestyle"],
    studioStyle: "Luxury marble lounge",
    bio: "A Nordic property presenter for architecture, interiors and considered living brands.",
  },
  {
    name: "Nia Brooks",
    slug: "nia-brooks",
    gender: "female",
    ageRange: "33-40",
    region: "United States",
    skinTone: "Deep cocoa",
    hair: "Natural coils, sculpted halo",
    bodyType: "Strong average",
    clothingStyle: "Sage wellness wrap",
    professionalStyle: "Wellness advocate",
    personality: "Grounded, kind, confident",
    voiceId: "nia-warm",
    accent: "American",
    languages: ["en"],
    speakingTone: "Warm",
    categories: ["Healthcare & Wellness", "Lifestyle", "Apps & Software"],
    studioStyle: "Wellness spa light",
    bio: "A US wellness presenter for clinics, mental-health apps and restorative consumer brands.",
  },
  {
    name: "Fatima Bello",
    slug: "fatima-bello",
    gender: "female",
    ageRange: "35-43",
    region: "Nigeria / West Africa",
    skinTone: "Deep umber",
    hair: "Wrapped silk scarf, sculpted edges",
    bodyType: "Full professional",
    clothingStyle: "Emerald medical-smart tailoring",
    professionalStyle: "Health and family services host",
    personality: "Reassuring, intelligent, maternal-professional",
    voiceId: "fatima-steady",
    accent: "Nigerian",
    languages: ["en", "ha", "yo"],
    speakingTone: "Professional",
    categories: ["Healthcare & Wellness", "General Marketing", "Business & Corporate"],
    studioStyle: "Modern glass office",
    bio: "A trusted health-services presenter for clinics, insurance and family-care campaigns across West Africa and the diaspora.",
  },
  {
    name: "Daniel Okoro",
    slug: "daniel-okoro",
    gender: "male",
    ageRange: "26-32",
    region: "Nigeria / West Africa",
    skinTone: "Medium espresso",
    hair: "Low fade, clean beard",
    bodyType: "Lean athletic",
    clothingStyle: "Graphite tech hoodie under blazer",
    professionalStyle: "Startup product host",
    personality: "Sharp, modern, conversational",
    voiceId: "daniel-fast",
    accent: "Nigerian",
    languages: ["en", "ig"],
    speakingTone: "Conversational",
    categories: ["Technology", "Apps & Software", "Ecommerce"],
    studioStyle: "Premium dark studio",
    bio: "A Lagos tech presenter for fintech, mobile products and founder-led software stories.",
  },
  {
    name: "Yasmin El-Sayed",
    slug: "yasmin-el-sayed",
    gender: "female",
    ageRange: "27-33",
    region: "Arab / Middle Eastern",
    skinTone: "Honey olive",
    hair: "Soft hijab drape in blush silk",
    bodyType: "Slim",
    clothingStyle: "Blush modest couture set",
    professionalStyle: "Beauty and modest fashion lead",
    personality: "Radiant, refined, contemporary",
    voiceId: "yasmin-silk",
    accent: "Arabic",
    languages: ["ar", "en"],
    speakingTone: "Friendly",
    categories: ["Fashion & Beauty", "Luxury", "Ecommerce"],
    studioStyle: "Editorial fashion set",
    bio: "A contemporary modest-fashion presenter for beauty, jewelry and Gulf retail campaigns.",
  },
  {
    name: "Hiroshi Tanaka",
    slug: "hiroshi-tanaka",
    gender: "male",
    ageRange: "44-52",
    region: "Japan",
    skinTone: "Fair neutral",
    hair: "Neat side part, salt and pepper",
    bodyType: "Average professional",
    clothingStyle: "Ink-black suit, no tie",
    professionalStyle: "Institutional brand chairman-host",
    personality: "Reserved, credible, exact",
    voiceId: "hiroshi-formal",
    accent: "Japanese",
    languages: ["ja", "en"],
    speakingTone: "Professional",
    categories: ["Business & Corporate", "Luxury", "General Marketing"],
    studioStyle: "Modern glass office",
    bio: "A senior Japanese corporate presenter for banks, houses of craft and formal brand films.",
  },
];
